feat: add reg page layout
Team-Cr/tamagotchi pull request #10
Opened 2022-11-30 08:57 UTC by hosyaeuw

### Какую задачу решаем
Добавлена верстка страницы Регистрации.

### Скриншоты/видяшка (если есть)

![image](https://user-images.githubusercontent.com/46399592/204751834-faf1a194-5333-4cbd-94d5-399437eb53aa.png)

2022-11-30 15:16 UTC, arudenko-offcl commented
Ждем фикса линтинга и официального приглашения на ревью 🙂

2022-12-04 10:39 UTC, lastmarsch commented on packages/client/src/pages/Registration/Registration.tsx
> +import { RegistrationForm } from '@/widgets/RegistrationForm';
Форма регистрации по FSD будет не виджетом, а feature: https://feature-sliced.design/docs/guides/examples/auth#features

2022-12-04 11:26 UTC, lastmarsch requested changes
Привет, хорошая работа, аккуратно и чисто написано, понравилось, что ты написал скрипт для конвертации и добавил компонент для типографии. Есть небольшие замечания по расположению файлов и согласованию с проектом, а также вопрос про использование контекста для формы, буду рада, если ты ответишь.

2022-12-04 11:26 UTC, lastmarsch commented on packages/client/src/shared/ui/Form/contexts/Context.ts
> +});
Объясни, пожалуйста, в каких случаях может понадобиться этот контекст? Почему ты его ввёл?

2022-12-04 11:26 UTC, lastmarsch commented on packages/client/src/shared/ui/Form/contexts/Context.ts
> +});
Расположение файла: контексты, провайдеры, хуки хранятся в папке `lib`

2022-12-04 11:26 UTC, lastmarsch commented on packages/client/src/shared/ui/Form/index.ts
> +export { useStateForm } from './hooks/useStateForm';
Не нашла, где ты используешь этот хук

2022-12-04 11:26 UTC, lastmarsch commented on packages/client/src/shared/ui/FormButton/ui/FormButton.tsx
> +};
Для кнопок появился отдельный `shared/ui` компонент `Button`, наверное, в `FormButton` уже нет необходимости

2022-12-04 11:26 UTC, lastmarsch commented on packages/client/src/shared/ui/Input/ui/Input.tsx
> +import { cn } from '@/shared/utils/classnames';
В проекте уже есть classnames, добавлена как зависимость в `package.json`

2022-12-04 11:26 UTC, lastmarsch commented on packages/client/src/widgets/RegistrationForm/ui/RegistrationForm.tsx
> +import { RegFormType } from '@/shared/hooks/useAuth';
Такой хук не нашелся

2022-12-04 11:26 UTC, lastmarsch commented on packages/client/src/widgets/RegistrationForm/ui/RegistrationForm.tsx
> +export const RegistrationForm: React.FC<Props> = ({ onSubmit, ...props }) => {
Форма регистрации по FSD будет не виджетом, а feature: https://feature-sliced.design/docs/guides/examples/auth#features

2022-12-04 15:12 UTC, hosyaeuw commented on packages/client/src/shared/assets/images/main.py
> +def convert_to_webp(source):
.png в .webp, но есть проблема с прозрачным фоном. Через раз работает, нужен ли вообще этот скрипт?

2022-12-04 15:14 UTC, hosyaeuw commented on packages/client/src/shared/ui/Form/contexts/Context.ts
> +});
контект нужен для прокидывания даты всей формы в дочерние элементы, чтобы не делать круговорот с пропсами, но потом я переписал структуру и он оказался избыточным. Удалить?

2022-12-04 15:18 UTC, lastmarsch commented on packages/client/src/shared/ui/Form/contexts/Context.ts
> +});
Лучше в таком случае удалить

2022-12-04 15:23 UTC, lastmarsch commented on packages/client/src/shared/assets/images/main.py
> +def convert_to_webp(source):
Если через раз, тогда думаю, стоит убрать и поискать альтернативы. Может быть, готовые онлайн конвертеры решили эту проблему

2022-12-05 09:39 UTC, arudenko-offcl requested changes
Постарайся не использовать `import * as React` и поправь замечания коллег. В остальном все 👌

2022-12-05 09:39 UTC, arudenko-offcl commented on packages/client/src/shared/assets/images/main.py
> +def convert_to_webp(source):
Ребята, мы же тут фронтенд изучаем. Давайте попробуем найти решение вокруг фронтовой инфраструктуры, например imagemin: https://github.com/imagemin/imagemin-webp

2022-12-05 09:39 UTC, arudenko-offcl commented on packages/client/src/shared/ui/Form/hooks/useStateForm.ts
> +import * as React from 'react';
А нам точно весь реакт тут нужен?)
Давай импортить только те методы, которые используются. В твоем случае useContext.

2022-12-05 09:39 UTC, arudenko-offcl commented on packages/client/src/shared/ui/Form/hooks/useStateForm.ts
> +import * as React from 'react';
Вижу, что от контекста ты откажешься, но замечание относительно импортов актуально все равно

2022-12-05 09:39 UTC, arudenko-offcl commented on packages/client/src/shared/ui/Form/ui/Form.tsx
> +import * as React from 'react';
Лучше почистить импорты, как я уже писал. 
`import React, {/* ... */} from 'react'`

2022-12-05 09:39 UTC, arudenko-offcl commented on packages/client/src/shared/utils/getFormValues.ts
> +  if (form) {
Некритично, но иногда такие случаи лучше читаются, если делаешь early return для пограничного случая:
```
if (!form) {
  return values;
}
const formData = new FormData(form);
return Object.fromEntries(formData);
```

2022-12-05 13:38 UTC, hosyaeuw commented on packages/client/src/shared/ui/Form/hooks/useStateForm.ts
> +import * as React from 'react';
Я переделаю под проект, как пишут ребята. Но разве import * as React from 'react' с помощью treeshake не отбросит ненужное? Импорт всего реакта, к которому не применяется treeshake это: import React from 'react' или я ошибаюсь?

2022-12-06 16:20 UTC, lastmarsch commented on packages/client/src/app/styles/index.scss
> +  font-weight: 400;
Эта строчка не нужна, потому что в --title-font уже указан font-weight

2022-12-06 16:23 UTC, lastmarsch commented on packages/client/src/features/RegistrationForm/ui/RegistrationForm.tsx
> +  onSubmit: (values: any) => void;
Any заменить на unknown?

2022-12-06 16:28 UTC, lastmarsch commented on packages/client/src/pages/Registration/index.ts
> +export { Registration } from './ui/Registration';
Переименуй название страницы в RegistrationPage, чтобы всё было однородно

2022-12-06 16:34 UTC, lastmarsch commented on packages/client/src/pages/Registration/ui/Registration.tsx
> +import { images } from '@/shared/assets';
Почему не импортируешь конкретные картинки?

2022-12-07 11:48 UTC, arudenko-offcl commented on packages/client/src/shared/ui/Form/hooks/useStateForm.ts
> +import * as React from 'react';
Это замечание в том числе и про хорошую практику написания кода. Явное лучше неявного  )

2022-12-10 21:05 UTC, lastmarsch approved these changes
Отлично!
1. Маленькое замечание: названия фич (корневой папки фичи) - это действия. То есть фича, которая осуществляет регистрацию - features/register, features/registerUser, etc. Сам компонент, экспортируемый из ui, переименовывать не нужно.
2. Проверь позицию страницы, у меня она улетела вверх, не так, как у тебя в описании PR. 
![image](https://user-images.githubusercontent.com/52976585/206875171-dee2e4a7-f607-43c4-8842-47602537769d.png)
3. Ты менял Input, поэтому при мердже с main нужно будет проверить, что остальные страницы работают и отображаются корректно.

2022-12-11 14:56 UTC, merged