Task 55 signup api
Team-Cr/tamagotchi pull request #11
Opened 2022-11-30 08:58 UTC by hosyaeuw

### Какую задачу решаем
подключил api к странице регистрации

2022-11-30 15:16 UTC, arudenko-offcl commented
Ждем фикса линтинга и официального приглашения на ревью 🙂

2022-12-04 11:51 UTC, lastmarsch requested changes
Здорово, что ты создал перечисления со всеми рутами, а также добавил HTTPClient. К сожалению, чтобы интегрировать твою работу в проект, придется подстроиться под уже написанный код. Перемести, пожалуйста, твои файлы api в `shared/lib/api` и добавь `axios`.

2022-12-04 11:51 UTC, lastmarsch commented on packages/client/src/shared/api/httpClient.ts
> +export const httpClient = new HTTP(BASE_URL);
К сожалению, в проекте уже присутствует `axios`.

2022-12-04 11:51 UTC, lastmarsch commented on packages/client/src/shared/api/AuthApi.ts
> +};
Посмотри, пожалуйста на структуру в `shared/lib/api`. Этот файл нужно будет переместить туда и отделить от него типы, положить их в соотв. папку `types`.

2022-12-04 11:51 UTC, lastmarsch commented on packages/client/src/shared/api/AuthApi.ts
> +}
В `shared/lib/api/auth.ts` уже есть `AuthAPI`. Добавь туда, пожалуйста, новые методы.

2022-12-04 11:51 UTC, lastmarsch commented on packages/client/src/shared/api/api.ts
> +};
Хорошо, что ты описал все руты! Пожалуйста, добавь в каждый `Routes` из файлов в `shared/lib/api` новые пути.

2022-12-05 09:49 UTC, arudenko-offcl reviewed
Учти комментарии коллег относительно структуры проекта и наличия уже существующих решений )

2022-12-05 09:49 UTC, arudenko-offcl commented on packages/client/src/pages/Registration/Registration.tsx
> +    registration(values);
НЕмного невнятное название коллбека, мб registerUser() хотя бы? 
И лучше оборачивать коллбеки в useCallback(). Иногда это бывает избыточно, но сейчас лучше приучить себя мемоизировать коллбеки.

2022-12-05 09:49 UTC, arudenko-offcl commented on packages/client/src/shared/api/AuthApi.ts
> +  public async checkAuth() {
Я бы отделил сущности, которые делают проверку возвращаемых данных от сущностей, которые просто ходят в апи и возвращают ответ.

2022-12-05 09:49 UTC, arudenko-offcl commented on packages/client/src/shared/assets/images/main.py
> +from pathlib import Path
Ну этот файл обсуждали в прошлом ПРе. Лучше убрать и воспользоваться пакетом от imagemin

2022-12-06 13:31 UTC, arudenko-offcl reviewed
Нужно удалить лишние файлы c обращением к апи и использовать axios, как это уже делает команда в `shared/lib/api/auth.ts`

Пиши на почту или сюда, если будут какие-то вопросы!

2022-12-06 13:31 UTC, arudenko-offcl commented on packages/client/src/shared/lib/convertingDataToSend.ts
> +  return data;
Тут предлагаю сделать чуть читаемее, во-первых, заиспользовать early return  и использовать reduce():
```
if (!isObject(data)) {
  return data
}
return Object.keys(data).reduce(() => { /* тут логика из forEach*/}, {})
```

2022-12-06 13:31 UTC, arudenko-offcl commented on packages/client/src/pages/Registration/ui/Registration.tsx
> +  const onSubmitHandler = (values: RegFormType) => {
Тут, я думаю, обертка вокруг registerUser не требуется, ты ведь не делаешь никакой доп логики, просто аргумент кидаешь дальше. Можно просто передать registerUser как обработчик сабмита.

2022-12-06 13:31 UTC, arudenko-offcl commented on packages/client/src/pages/Registration/ui/Registration.tsx
> +  const onSubmitHandler = (values: RegFormType) => {
Правда, я не виджу проверки на валидацию введенных данных. Планируешь ее добавить ?

2022-12-06 13:31 UTC, arudenko-offcl commented on packages/client/src/shared/hooks/useAuth.tsx
> +import * as React from 'react';
ЛУчше не импортировать сразу весь реакт )) 

Импорти только необходимые тебе методы

2022-12-06 13:31 UTC, arudenko-offcl commented on packages/client/src/shared/utils/httpClient/HttpClient.ts
> +      const xhr = new window.XMLHttpRequest();
Уже в проекте есть axios, как писали. Давай использовать его вместо xhr, а ненужные файлики просто дропнем?

2022-12-06 13:35 UTC, arudenko-offcl commented
**UPD**: НЕсколько запутался в коммитах, прошу прощения! Вижу, что ты стал использовать axios. Давай удалим `packages/client/src/shared/utils/httpClient/HttpClient.ts` и будет ок )

2022-12-06 17:52 UTC, hosyaeuw commented on packages/client/src/pages/Registration/ui/Registration.tsx
> +  const onSubmitHandler = (values: RegFormType) => {
да, просто с командой решили позже сделать

2022-12-06 21:04 UTC, lastmarsch approved these changes
Все отлично, у меня только есть пожелания по расположению функций, связанных с регистрацией

2022-12-06 21:04 UTC, lastmarsch commented on packages/client/src/shared/hooks/useAuth.tsx
> +};
Как я уже упоминала в https://github.com/Team-Cr/tamagotchi/pull/10, считаю, что эту часть следует перенести в фичу RegistrationForm, так как используется только в ней.

2022-12-06 21:04 UTC, lastmarsch commented on packages/client/src/pages/Registration/ui/Registration.tsx
> +    registerUser(values);
См. коммент к useAuth

2022-12-07 11:49 UTC, arudenko-offcl approved these changes
👌

2022-12-08 07:59 UTC, arudenko-offcl commented
Ждем мерж 🙂

2022-12-11 15:02 UTC, merged