Fix/consistency
Team-Cr/tamagotchi pull request #12
Opened 2022-12-03 20:00 UTC by lastmarsch

### Какую задачу решаем
- Приведение кода к общему и согласованному виду (правильное расположение папок)
- Правка css:
  - Правка overflow на некоторых страницах
  - Добавление css variables для инпута и кнопок + для моб.версии  
- Замена некоторых png на svg (для поддержания стиля и уменьшения времени загрузки):
  - Кнопка "назад" в лидерборде
  - Иконка лидерборда и настроек на странице игры
- Добавлен svgr для работы с svg
- Поправлены стили модалки + теперь можно скрыть "крестик"

### Скриншоты
![Лидерборд](https://user-images.githubusercontent.com/52976585/205459456-6d78eca3-e7f2-4d30-a5b7-4acfc5a17207.png)
![Главная страница](https://user-images.githubusercontent.com/52976585/205459466-159a6120-bd1b-4b6c-9968-a553136ab3a1.png)
![Логин](https://user-images.githubusercontent.com/52976585/205459469-83f72aae-f465-4858-88e9-337f2da364b7.png)
![Профиль](https://user-images.githubusercontent.com/52976585/205459470-1f7605ed-5c79-4c2a-aa3e-1fbd1eef748a.png)
![Модалка без крестика](https://user-images.githubusercontent.com/52976585/205459473-5d05c658-fe87-48f6-9e5a-3c0104b6091e.png)

2022-12-05 08:52 UTC, DaniilBabakin requested changes
Привет. Перенести конфиг ActionBlock'ов хорошая идея 
Теперь что я хочу подметить:
1) В css action-block было правильным , если опираться на БЭМ ( https://ru.bem.info/methodology/quick-start/#%D0%9C%D0%B8%D0%BA%D1%81 - пункт **вложенность**) 
2) Перенос типов в отдельную папку MainContainer'a влечет за собой длинные импорты, сложности с нахождением его в будущем. add.d.ts создан как раз для типов, которые используются по всему приложению. Далее тип LevelOrHpBars будет использован и в редаксе. Также я проверил размер иконок в 60px , они выглядят маленькими на моем 1920x1080 
3) Предложенные svg черного цвета без заливки, они будут странно смотреться на фоне цветных иконок, кота и полосок
4) Через модули , видимо, пишет вся команда, так что придется привыкать )

2022-12-05 09:14 UTC, lastmarsch commented
@DaniilBabakin 
1. Я поменяла название с "action-block" на "actionBlock", чтобы обращаться к классу без квадратных скобок. Не `css['action-block']`, a 'css.actionBlock'. 
2. Окей, верну add.d.ts (Почему он так называется?)
3. Верну png 🤷‍♀️

Пожалуйста, пиши комментарии к конкретным кускам кода, чтобы было удобнее искать и исправлять.

2022-12-05 10:01 UTC, lastmarsch commented
@DaniilBabakin Исправила замечания, вернула иконки:
![Tamagotchi](https://user-images.githubusercontent.com/52976585/205608927-4af93024-c64c-4105-9e91-d2669a989469.png)

2022-12-05 10:07 UTC, arudenko-offcl commented
Касательно нейминга можно посмотреть в сторону решений, упрощающих формирование класснеймов:
https://ru.bem.info/technologies/bem-react/classname/
https://www.npmjs.com/package/bem-react-classname

Попробуйте завести пр с примером использования, обсудить в команде и решить, что использовать. А может и не использовать вовсе ) Но мне бы тоже использовать `['block__elem'] `было бы неудобно.

2022-12-05 10:14 UTC, arudenko-offcl commented on packages/client/src/pages/ProfilePage/ui/ProfileAvatar/ui/ProfileAvatar.tsx
> +          src={image || ResourceAPI.getResource(avatar || '')}
Лучше предварительно прелоадить аватар и затем класть верстку

2022-12-05 10:14 UTC, arudenko-offcl commented on packages/client/src/pages/ProfilePage/ui/ProfileModal/ui/ProfileModal.tsx
> +  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
Стоит мемоизировать коллбеки тут и в остальных местах

2022-12-05 12:39 UTC, grizzlygarillaz commented on packages/client/src/pages/ProfilePage/ui/ProfileModal/ui/ProfileModal.tsx
> +  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
А разве все колбеки стоит мемоизировать?
Как я понимаю, это необходимо для снижения количества ререндеров, но в данном случае это разве не лишнее?
Просто сейчас я вписал useCallbackм и количество ререндеров осталось тем же.
Если я не прав, можно пожалуйста ссылку на ресурс, где можно подробнее об этом узнать

2022-12-05 14:58 UTC, lastmarsch commented on packages/client/src/pages/ProfilePage/ui/ProfileAvatar/ui/ProfileAvatar.tsx
> +          src={image || ResourceAPI.getResource(avatar || '')}
Можешь, пожалуйста, поподробнее сказать, что ты имеешь в виду?

2022-12-05 15:33 UTC, anuta199212 commented on packages/client/src/pages/ProfilePage/ui/ProfileAvatar/ui/ProfileAvatar.tsx
> +    <>
Здесь наверно не имеет смысла использовать React.Fragment.

2022-12-05 15:37 UTC, lastmarsch commented
Вынесла аватар в отдельный компонент Avatar. (@grizzlygarillaz)

2022-12-05 19:22 UTC, grizzlygarillaz commented
Хотел перезаписать коммит, но получилось как всегда...
Буду благодарен, если кто подскажет, как ролбекать запушенный коммит или как в таких ситуациях поступать-_-

2022-12-06 12:51 UTC, arudenko-offcl commented
@grizzlygarillaz а что ты хотел сделать, не очень понял? Если запушил лишнее и хочешь  отменить, то попробуй git revert.

2022-12-06 12:59 UTC, grizzlygarillaz commented
> @grizzlygarillaz а что ты хотел сделать, не очень понял? Если запушил лишнее и хочешь отменить, то попробуй git revert.

Я так и сделал, но как я понял коммит не уберётся в любом случае? Или что-то дополнительно нужно было сделать?

2022-12-06 13:09 UTC, arudenko-offcl commented
> Я так и сделал, но как я понял коммит не уберётся в любом случае? Или что-то дополнительно нужно было сделать?
Коммит в истории останется, но добавится коммит с префиксом Revert, в котором отменится дифф из коммита, который ты ревертнул. Это нормальное ожидаемое поведение.

Так же можешь в свободное время почитать про `git rebase -i ` ) Это факультативно )

2022-12-06 13:13 UTC, arudenko-offcl commented on packages/client/src/pages/ProfilePage/ui/ProfileAvatar/ui/ProfileAvatar.tsx
> +          src={image || ResourceAPI.getResource(avatar || '')}
Уже вижу нужные изменения, все ок

2022-12-06 13:13 UTC, arudenko-offcl approved these changes

2022-12-07 11:51 UTC, DaniilBabakin approved these changes
Привет! Не увидел каких-то серьезных ошибок, ровно как и средних-маленьких 
Много хорошего кода добавилось, очень очень плотный рефакторинг 👍

2022-12-07 11:51 UTC, DaniilBabakin commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardEntry/ui/LeaderboardEntry.tsx
> +        <Avatar src={avatarUrl} className={css.entry__avatar} />
Хорошая идея, этот компонент еще 3-4 раза будет переиспользоваться 👍

2022-12-07 12:05 UTC, merged