Task 11 routing
Team-Cr/tamagotchi pull request #18
Opened 2022-12-17 17:53 UTC by DaniilBabakin

### Какую задачу решаем
Добавил роутинг, а также анимации к ним при помощи Framer Motion

2022-12-17 19:07 UTC, lastmarsch requested changes
Привет, роутинг и анимация работают, всё окей. У меня есть вопросы по организации кода и предложение по вынесению этой части с роутингом (начиная с `AnimatePresence`) в отдельный провайдер.

2022-12-17 19:07 UTC, lastmarsch commented on packages/client/src/shared/ui/ArrowBack/ui/ArrowBack.tsx
> +  const handleClick = useCallback(() => {
Эту функцию можно назвать более понятно для разработчика, типа `goBack`

2022-12-17 19:07 UTC, lastmarsch commented on packages/client/src/widgets/Transitions/ui/TransitionBlock.tsx
> +export const TransitionBlock: React.FC<TransitionBlockProps> = ({
Заметила, что ты оборачиваешь этим компонентом каждую страницу, может быть, имеет смысл эту обертку вынести из каждого компонента наверх.

2022-12-17 20:58 UTC, DaniilBabakin commented on packages/client/package.json
> +    "react-router-dom": "^6.5.0"
Да,точно

2022-12-17 20:59 UTC, DaniilBabakin commented on packages/client/src/app/App.tsx
> +// startServiceWorker();
На время дева убрал сервис воркеры, так как они после релоада выдают кешированную версию и приходится каждый раз f5 нажимать + роутинг не работал корректно, хотел расскоментить после добавления анимаций на страницу

2022-12-17 21:04 UTC, DaniilBabakin commented on packages/client/src/widgets/Transitions/ui/TransitionBlock.tsx
> +export const TransitionBlock: React.FC<TransitionBlockProps> = ({
Немного не понял, что значит вынести наверх

2022-12-17 21:04 UTC, DaniilBabakin commented on packages/client/src/shared/ui/ArrowBack/ui/ArrowBack.tsx
> +  const handleClick = useCallback(() => {
Ага , хорошо

2022-12-17 21:06 UTC, DaniilBabakin commented on packages/client/src/pages/index.ts
> +export { LeaderboardPage } from './LeaderboardPage';
Без этого файла у меня было 7 импортов вместо 1

2022-12-17 21:08 UTC, DaniilBabakin commented on packages/client/src/features/RegistrationForm/ui/RegistrationForm.tsx
> +        <Input placeholder='Email' type='text' name='email' />
Изначально типы не были заданы

2022-12-17 21:10 UTC, DaniilBabakin commented on packages/client/src/app/App.tsx
> +          ].map((item) => (
Ты про Date.now в <Route> или в appRoutes?

2022-12-17 22:40 UTC, lastmarsch commented on packages/client/src/app/App.tsx
> +          ].map((item) => (
Про тот, который в appRoutes

2022-12-17 22:47 UTC, lastmarsch commented on packages/client/src/pages/index.ts
> +export { LeaderboardPage } from './LeaderboardPage';
Да, но ты все равно сделаешь эти 7 импортов только в одном файле. В принципе, этот момент для меня не особо критичен

2022-12-17 22:49 UTC, lastmarsch commented on packages/client/src/widgets/Transitions/ui/TransitionBlock.tsx
> +export const TransitionBlock: React.FC<TransitionBlockProps> = ({
Имела в виду, что можно вынести этот блок сюда (но сама не проверяла, будет это работать или нет):
```ts
{appRoutes.map(({ element, route, isProtected = false }) => (
    <Route
      path={route}
      element={isProtected ? <ProtectedMainRoute /> : <ProtectedLoginRoute />}
      key={Date.now()}
    >
      // <TransitionBlock>
      <Route path={route} element={element} />
      // </TransitionBlock>
    </Route>
  ))}
```

2022-12-18 10:57 UTC, DaniilBabakin commented on packages/client/src/widgets/Transitions/ui/TransitionBlock.tsx
> +export const TransitionBlock: React.FC<TransitionBlockProps> = ({
Думаю работать будет, но это ухудшит понимание кода , т.к грубо говоря `<main>` выводишь наверх.

2022-12-19 10:37 UTC, arudenko-offcl reviewed
Несколько вопросов

2022-12-19 10:37 UTC, arudenko-offcl commented on packages/client/src/app/providers/RouterProvider/lib/appRoutes.tsx
> +  isProtected?: 'main' | 'login' ;
Как правило, переменные с префиксом is подразумевают, что хранят в себе boolean.

Давай лучше protectionType, redirectType и тп

2022-12-19 10:37 UTC, arudenko-offcl commented on packages/client/src/app/services/startServiceWorker.ts
> +  // }
+

2022-12-19 10:37 UTC, arudenko-offcl commented on packages/client/src/features/RegistrationForm/ui/RegistrationForm.tsx
> +        <Input placeholder='Email' type='text' name='email' />
У инпута с email тип был задан )

2022-12-19 10:37 UTC, arudenko-offcl commented on packages/client/src/index.tsx
> +          <RouterProvider>
Почему не обернешь все в `<Router>` внутри роутер-провайдера?

2022-12-19 10:37 UTC, arudenko-offcl commented on packages/client/src/app/providers/RouterProvider/ui/RouterProvider.tsx
> +                key={Date.now()}
Могут быть совпадающие ключи

2022-12-19 10:37 UTC, arudenko-offcl commented on packages/client/src/widgets/Transitions/ui/TransitionBlock.tsx
> +export const TransitionBlock: React.FC<TransitionBlockProps> = ({
Согнласен с @DaniilBabakin в данном случае, лучше явно, чем неявно.

2022-12-21 11:29 UTC, lastmarsch approved these changes
Отлично, у меня нет замечаний

2022-12-21 12:43 UTC, arudenko-offcl approved these changes
LGTM 👌

2022-12-21 13:19 UTC, merged