Task 56 api profile data change
Team-Cr/tamagotchi pull request #4
Opened 2022-11-28 12:43 UTC by grizzlygarillaz

### Какую задачу решаем
56 - Api смена данных в профиле
22 - API для работы с аватаркой
20 - API для смены пароля

### TBD (если есть)
Как я понял, работа с апи будет реализована через редакс, но с ним я ещё не начал даже разбираться...

2022-11-28 17:31 UTC, anuta199212 commented on packages/client/vite.config.ts
> +    __BASE_URL__: process.env.BASE_URL
Хорошая идея - вынести `BASE_URL` в `.env` файл.

2022-11-28 17:35 UTC, anuta199212 reviewed
Спасибо за работу.
Здесь у меня замечания также как и в #3  по оформлению (возможно стоит сделать `merge` ветки PR-3 в текущую?).

2022-11-29 11:18 UTC, arudenko-offcl commented
Привет, ребята. Смотрю ПР, не теряйте

2022-11-29 13:01 UTC, arudenko-offcl requested changes
Старайся все же делать ПР более атомарными, решающими одну задачу. 
Это важно на коммерческих боевых проектах, например, если в одной из задач найдут багу, придется откатывать пр со всеми изменениями.

2022-11-29 13:01 UTC, arudenko-offcl commented on packages/client/src/shared/ui/Modal/ui/Modal.tsx
> +        {/* Тестовый див. ВАЖНО: Задавай высоту именно нижнего(тестового) дива, а не modal__body */}
А почему так?

2022-11-29 13:28 UTC, lastmarsch commented on packages/client/src/shared/ui/Button/ui/Button.module.scss
> +@import 'https://fonts.googleapis.com/css2?family=VT323&display=swap';
После того, как я смёрджу https://github.com/Team-Cr/tamagotchi/pull/2, убери, пожалуйста, импорт шрифтов и замени всё, что возможно, на переменные из `global.scss`. Так будет легче контролировать стиль по всему приложению

2022-11-30 14:58 UTC, arudenko-offcl commented on packages/client/src/pages/index.tsx
> +export const Routing = () => {
Принимается )

2022-12-01 12:04 UTC, arudenko-offcl reviewed
Привет! Вижу, что не все замечания/вопросы поправлены. Подскажи, все ли понятно, требуется ли какая-то помощь?

2022-12-01 12:04 UTC, arudenko-offcl commented on packages/client/src/pages/index.tsx
> +      <Route path='/profile' element={<Profile/>}/>
Не поправил пока (

2022-12-01 12:04 UTC, arudenko-offcl commented on packages/client/src/pages/profile/index.tsx
> +      <div className={styles.profile__container}>
Пожалуйста, кивни, что обсудите с командой нейминг стилей )

2022-12-01 12:04 UTC, arudenko-offcl commented on packages/client/src/shared/lib/classname/useClassName.ts
> +export interface ClassArray extends Array<ClassValue> {} //eslint-disable-line @typescript-eslint/no-empty-interface
Не поправил (

2022-12-01 12:04 UTC, arudenko-offcl commented on packages/client/src/shared/ui/Button/ui/Button.module.scss
> +@import 'https://fonts.googleapis.com/css2?family=VT323&display=swap';
.

2022-12-01 12:05 UTC, grizzlygarillaz commented on packages/client/src/pages/profile/index.tsx
> +      <div className={styles.profile__container}>
Обсудили

2022-12-01 12:11 UTC, grizzlygarillaz commented on packages/client/src/shared/lib/classname/useClassName.ts
> +export interface ClassArray extends Array<ClassValue> {} //eslint-disable-line @typescript-eslint/no-empty-interface
А у меня потом ошибки типизации идут, если убираешь (
![изображение](https://user-images.githubusercontent.com/26850602/205049620-52dd7d05-4e2e-4d51-94a1-d11bfa08691c.png)

2022-12-01 12:44 UTC, grizzlygarillaz commented on packages/client/src/shared/lib/classname/useClassName.ts
> +export interface ClassArray extends Array<ClassValue> {} //eslint-disable-line @typescript-eslint/no-empty-interface
https://github.com/rsuite/rsuite/blob/5d35f6c1639a49174274ccabf2edd3b40a388c32/src/utils/useClassNames.ts#L15
Это откуда брал реф на функционал

2022-12-01 12:46 UTC, grizzlygarillaz commented on packages/client/src/pages/index.tsx
> +      <Route path='/profile' element={<Profile/>}/>
Тут проворонил, каюсь

2022-12-01 13:53 UTC, grizzlygarillaz commented on packages/client/package.json
> +    "vite-plugin-environment": "1.1.3",
А и видимо нам переменные .env надо в .env.sample кидать, иначе они только локально будут. 
После yarn bootstrap чистится.
Ну либо каждому дублировать значение в .env

2022-12-01 14:01 UTC, lastmarsch commented on packages/client/package.json
> +    "vite-plugin-environment": "1.1.3",
Да, лучше в sample сохранить.

2022-12-01 14:04 UTC, lastmarsch commented on packages/client/src/app/App.tsx
> +  return <><Profile/></>;
Не забудь убрать эту страницу перед мерджем

2022-12-02 13:49 UTC, anuta199212 approved these changes

2022-12-03 08:26 UTC, arudenko-offcl commented on packages/client/src/shared/lib/classname/useClassName.ts
> +export interface ClassArray extends Array<ClassValue> {} //eslint-disable-line @typescript-eslint/no-empty-interface
Окей, принимается)

2022-12-03 08:26 UTC, arudenko-offcl approved these changes

2022-12-03 08:50 UTC, merged