Add login page layout
Team-Cr/tamagotchi pull request #5
Opened 2022-11-28 15:52 UTC by anuta199212

### Какую задачу решаем
Добавлена верстка страницы авторизации. 
Ссылки на задачи: [1](https://linear.app/kxnkxv/issue/CRNG-1/stranica-vhoda) и [14](https://linear.app/kxnkxv/issue/CRNG-14/stranica-avtorizacii-bez-logiki)

### Скриншоты/видяшка (если есть)
![изображение](https://user-images.githubusercontent.com/38813390/204321470-831ca11f-c296-4e08-b37d-f000d9a6e99d.png)

![изображение](https://user-images.githubusercontent.com/38813390/204321737-f6caafad-21f4-4aa2-8399-f2d0b18b4197.png)

### TBD (если есть)

2022-11-28 18:55 UTC, DaniilBabakin commented
Привет! Начинаю ревью кода

2022-11-28 19:03 UTC, DaniilBabakin commented
Анна, работа сделана отлично! Отмечу хорошее разделение на компоненты, ни в одном из них не увидел избыток логики 👍 Молодец , что вынесла стили в переменные. Поправь, пожалуйста, верстку и возвращайся с новым скриншотом!

2022-11-28 19:03 UTC, DaniilBabakin requested changes

2022-11-28 19:03 UTC, DaniilBabakin commented on packages/client/src/shared/ui/Link/ui/Link.module.scss
> +  cursor: pointer;
Необходимо увеличить font-size и сделать его определенным числом. Чтобы при уменьшении разрешения ничего не вылезало можно применить media запросы 👌

2022-11-29 09:13 UTC, anuta199212 commented on packages/client/src/shared/ui/Button/ui/Button.module.scss
> +  color: white;
Исправила здесь и по всему проекту.

2022-11-29 09:13 UTC, anuta199212 commented on packages/client/src/pages/SignInPage/ui/SignInPage.module.scss
> +  background-image: url('../../../shared/assets/images/fish-pattern-inversed.png');
Добавила

2022-11-29 09:14 UTC, anuta199212 commented on packages/client/src/shared/ui/Input/ui/Input.module.scss
> +  padding: 5px;
Исправила.

2022-11-29 10:55 UTC, DaniilBabakin approved these changes
Аппруваю)

2022-11-29 13:11 UTC, arudenko-offcl requested changes
Постарайся вынести в константы общие значения, такие как font-size, а так же убери пересекающиеся с ПРом @lastmarsch стили для body{}

2022-11-29 13:40 UTC, lastmarsch commented on packages/client/src/app/App.tsx
> +import { SignInPage } from '@/pages/SignInPage/ui/SignInPage';
Здесь должен быть импорт public API страницы: `@/pages/SignInPage`

2022-11-29 13:40 UTC, lastmarsch commented on packages/client/src/shared/lib/auth/AuthAPI.ts
> +  const endpoint = '/signin';
Эту константу тоже можно вынести за пределы функции

2022-11-29 13:40 UTC, lastmarsch commented on packages/client/src/shared/ui/Input/ui/Input.tsx
> +        placeholder={props.placeholder}
Можно деструктуризировать props выше для повышения читаемости или вообще написать это как `<input {...props}/>`, так как названия пропсов повторяют названия пропсов `input`.

2022-11-29 13:40 UTC, lastmarsch commented on packages/client/src/shared/ui/Input/ui/Input.tsx
> +interface InputProps {
Думаю, лучше отнаследовать этот интерфейс от ` InputHTMLAttributes<HTMLInputElement>`, так как данный компонент сохраняет исходный функционал инпута.

2022-11-30 08:11 UTC, anuta199212 commented on packages/client/src/app/App.tsx
> +import { SignInPage } from '@/pages/SignInPage/ui/SignInPage';
Поправила

2022-11-30 08:11 UTC, anuta199212 commented on packages/client/src/shared/ui/Input/ui/Input.tsx
> +        placeholder={props.placeholder}
Исправила

2022-11-30 08:11 UTC, anuta199212 commented on packages/client/src/shared/ui/Input/ui/Input.tsx
> +interface InputProps {
Исправила

2022-11-30 08:11 UTC, anuta199212 commented on packages/client/src/pages/SignInPage/ui/SignInPage.tsx
> +            onChange={(e) => setForm({ ...form, login: e.target.value })}
Исправила

2022-11-30 08:13 UTC, anuta199212 commented
Стили поправила с учетом констант из PR от @lastmarsch.

2022-11-30 15:01 UTC, arudenko-offcl approved these changes
👌

2022-11-30 15:51 UTC, merged