Add login page API
Team-Cr/tamagotchi pull request #6
Opened 2022-11-28 15:54 UTC by anuta199212

### Какую задачу решаем
добавлена работа с API страницы авторизации.
Ссылка на задачу в Linear: [54](https://linear.app/kxnkxv/issue/CRNG-54/api-stranicy-logina).

2022-11-29 11:03 UTC, anuta199212 commented
Забрала последние изменения из #5.

2022-11-29 13:19 UTC, arudenko-offcl requested changes
Нужно вынести обработчики кликов/других пользовательских действий в useCallback()  и унести общие стили в packages/client/src/app/styles/index.scss

2022-11-29 13:19 UTC, arudenko-offcl commented on packages/client/src/pages/SignInPage/ui/SignInPage.module.scss
> +  background-image: url('../../../shared/assets/images/fish-pattern-inversed.png');
Стили, общие для всех страниц, лучше унести куда-нибудь в packages/client/src/app/styles/index.scss, посмотри как сделано [тут](https://github.com/Team-Cr/tamagotchi/pull/2/files#diff-6f38ec81679b987eca8abc3c0f864fc8c3df6d6ece6410fc729cae48133fc2eb)

2022-11-29 13:19 UTC, arudenko-offcl commented on packages/client/src/pages/SignInPage/ui/SignInPage.tsx
> +    <form onSubmit={(e) => onSubmit(e, form)}>
Хендлеры лучше хранить внутри компонента, обернув в useCallback()
И не инлайни метод-обработчик, просто передавай ссылку на него )

2022-11-29 17:24 UTC, DaniilBabakin approved these changes

2022-11-30 08:19 UTC, anuta199212 commented on packages/client/src/pages/SignInPage/ui/SignInPage.module.scss
> +  background-image: url('../../../shared/assets/images/fish-pattern-inversed.png');
Исправила. Стили поправила с учетом PR-2.

2022-11-30 08:19 UTC, anuta199212 commented on packages/client/src/pages/SignInPage/ui/SignInPage.tsx
> +    <form onSubmit={(e) => onSubmit(e, form)}>
Исправила

2022-11-30 15:02 UTC, arudenko-offcl approved these changes
👌

2022-11-30 15:58 UTC, merged